[pytest]
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Запускает все UI автотесты
    smoke: Запускает все smoke автотесты
    regression: Запускает все регрессионные автотесты
    registration: Запускает все автотесты регистрации
    authorization: Запускает все автотесты авторизации
    courses: Запускает все автотесты для курсов
    dashboard: Тесты рабочей панели