from enum import Enum


class AllureTag(str, Enum):
    COURSES = "COURSES"
    DASHBOARD = "DASHBOARD"
    REGRESSION = "REGRESSION"
    USERS_LOGIN = "USERS_LOGIN"
    NAVIGATION = "NAVIGATION"
    REGISTRATION = "REGISTRATION"
    AUTHORIZATION = "AUTHORIZATION"
